spring:
  profiles.active: dev

---
############################
# PROFILE DEV DEFAULT
############################
spring:
  profiles: dev
  rabbitmq:
    # addresses:
    host: ${RABBIT_MQ_BUS_HOST}
    port: ${RABBIT_MQ_BUS_PORT}
    username: admin#1
    password: ${RABBIT_MQ_BUS_PASSWORD}

management.security.enabled: false

zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    ice-account-ms: /account/**
    ice-auth-ms: /auth/**

ribbon.eureka.enabled: true 

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:  
  port: ${ICE_GETWAY_MS_PORT}

security:
  basic:
    enabled: false
  user:
    name: admin#1
    password:  ${ICE_GETWAY_MS_PASSWORD}


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

logging:
  file: logs/default_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.hibernate: WARN

---
############################
# PROFILE DCKER
############################
spring:
    profiles: docker

server:  
  port: 8400

security:
  basic:
    enabled: false
  user:
    name: user
    password: ${CONFIG_SERVICE_PASSWORD}

logging:
  file: logs/docker_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.hibernate: WARN

---
############################
# PROFILE UAT
############################
spring:
    profiles: uat

server:  
  port: 8500

security:
  basic:
    enabled: false
  user:
    name: user
    password: ${CONFIG_SERVICE_PASSWORD}

logging:
  file: logs/uat_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.hibernate: WARN

---
############################
# PROFILE PRODUCTION MYSQL
############################
spring:
  profiles: prod

server:  
  port: 8600

security:
  basic:
    enabled: false
  user:
    name: user
    password: ${CONFIG_SERVICE_PASSWORD}

logging:
  file: logs/prod_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.hibernate: WARN

---
############################
# PROFILE PRODUCTION ORACLE
############################
spring:
  profiles: prod-oracle

server:  
  port: 8700

security:
  basic:
    enabled: false
  user:
    name: user
    password: ${CONFIG_SERVICE_PASSWORD}

logging:
  file: logs/prod_oracle_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.hibernate: WARN
