spring:
  profiles.active: dev

---
############################
# PROFILE DEV DEFAULT
############################
spring:
  profiles: dev

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

security:
  basic:
    enabled: false
  user:
    name: user
    password: ${CONFIG_SERVICE_PASSWORD}

---
############################
# PROFILE DOCKER
############################
spring:
  profiles: docker

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

security:
  basic:
    enabled: false
  user:
    name: user
    password: ${CONFIG_SERVICE_PASSWORD}
