spring:
  profiles.active: default

---
############################
# PROFILE DEV DEFAULT
############################
spring:
  profiles: default

configuration:  
  projectName: configclientDev

server:  
  port: 8300

message:  
  greeting: Hello from the configuration dev
security:
  basic:
    enabled: false
  user:
    name: user
    password: ${CONFIG_SERVICE_PASSWORD}

logging:
  file: logs/default_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.hibernate: WARN

---
############################
# PROFILE DCKER
############################
spring:
    profiles: docker

configuration:  
  projectName: configclientDocker

server:  
  port: 8400

message:  
  greeting: Hello from the configuration docker
security:
  basic:
    enabled: false
  user:
    name: user
    password: ${CONFIG_SERVICE_PASSWORD}

logging:
  file: logs/docker_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.hibernate: WARN

---
############################
# PROFILE UAT
############################
spring:
    profiles: uat

configuration:  
  projectName: configclientUAT

server:  
  port: 8500

message:  
  greeting: Hello from the configuration uat
security:
  basic:
    enabled: false
  user:
    name: user
    password: ${CONFIG_SERVICE_PASSWORD}

logging:
  file: logs/uat_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.hibernate: WARN

---
############################
# PROFILE PRODUCTION MYSQL
############################
spring:
  profiles: prod

configuration:  
  projectName: configclientprod

server:  
  port: 8600

message:  
  greeting: Hello from the configuration prod
security:
  basic:
    enabled: false
  user:
    name: user
    password: ${CONFIG_SERVICE_PASSWORD}

logging:
  file: logs/prod_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.hibernate: WARN

---
############################
# PROFILE PRODUCTION ORACLE
############################
spring:
  profiles: prod-oracle

configuration:  
  projectName: configclientprod-oracle

server:  
  port: 8700

message:  
  greeting: Hello from the configuration prod-oracle
security:
  basic:
    enabled: false
  user:
    name: user
    password: ${CONFIG_SERVICE_PASSWORD}

logging:
  file: logs/prod_oracle_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.hibernate: WARN
